# Stage 1: Extract layers of the app
FROM adoptopenjdk:17-jdk-hotspot AS build
ARG JAR_FILE=build/libs/*.jar
ADD ${JAR_FILE} app.jar
RUN mkdir /app \
  && cd /app \
  && jar xf /app.jar

# Stage 2: Build layered container image
FROM adoptopenjdk:17-jre-hotspot
COPY --from=build /app/BOOT-INF/lib /app/lib
COPY --from=build /app/META-INF /app/META-INF
COPY --from=build /app/BOOT-INF/classes /app
VOLUME /tmp
WORKDIR /app
EXPOSE 8081
ENTRYPOINT ["java","-cp","/app:/app/lib/*","de.woock.VereinApp"]
